---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      serviceAccount: sa-with-anyuid
      serviceAccountName: sa-with-anyuid
      containers:
      - name: drupal
        image: drupal:10.2.6-php8.2-apache-bookworm
        ports:
        - containerPort: 80
