---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      serviceAccount: sa-with-anyuid
      serviceAccountName: sa-with-anyuid
      containers:
      - name: drupal
        image: 'image-registry.openshift-image-registry.svc:5000/institucional-drupal-dev/drupal-padrao:latest'
        ports:
        - containerPort: 80
