---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: drupal-mysql-vol
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      containers:
      - name: mysql
        image: mysql:8.4
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: drupal-mysql-vol
        ports:
        - containerPort: 3306
        env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: drupal-database
            - name: MYSQL_USER
              value: drupal-user
            - name: MYSQL_PASSWORD
              value: drupal-pass