apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drupal-base

resources:
# namespace
- drupal-ns.yaml
# database
- drupal-mysql-pvc.yaml
- drupal-mysql-deploy.yaml
- drupal-mysql-svc.yaml
# cms-permissions
- drupal-permission-sa.yaml
- drupal-permission-role.yaml
- drupal-permission-rolebinding.yaml
# cms
- drupal-deploy.yaml
- drupal-svc.yaml
- drupal-route.yaml