apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-to-scc-anyuid
  namespace: drupal-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-anyuid
subjects:
- kind: ServiceAccount
  name: sa-with-anyuid
